
version: "3.8"
services:
  levichat:
    image: tommy6769/levichat:latest
    build: .
    container_name: levichat
    ports:
      - "80:3000"
    environment: 
      - PORT=3000
    volumes: 
      - ./:/app
    command: ["node", "app.js"]
